# Generated by Django 3.1 on 2020-10-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eas',
            table='eas',
        ),
    ]
