# Generated by Django 3.1 on 2021-05-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_auto_20210517_1641'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseDirectory',
        ),
        migrations.DeleteModel(
            name='ClientDirectory',
        ),
        migrations.DeleteModel(
            name='NumberCompetitor',
        ),
    ]
