# Generated by Django 3.1 on 2020-10-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20201028_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbrella_brand', models.TextField(blank=True)),
                ('source', models.TextField(blank=True)),
                ('tn_fv', models.TextField(blank=True)),
                ('registration_tm', models.TextField(blank=True)),
                ('corporation', models.TextField(blank=True)),
                ('manufacturer', models.TextField(blank=True)),
                ('country', models.TextField(blank=True)),
                ('rx_otc', models.TextField(blank=True)),
                ('trade_name_rus', models.TextField(blank=True)),
                ('trade_name_eng', models.TextField(blank=True)),
                ('pack_key', models.TextField(blank=True)),
                ('fv_short', models.TextField(blank=True)),
                ('type_packing_fv', models.TextField(blank=True)),
                ('dosage', models.TextField(blank=True)),
                ('volwe', models.TextField(blank=True)),
                ('numero', models.TextField(blank=True)),
                ('tastes_and_parentheses_fv', models.TextField(blank=True)),
                ('vendor_code', models.TextField(blank=True)),
                ('divisible_packaging', models.TextField(blank=True)),
                ('size', models.TextField(blank=True)),
                ('age', models.TextField(blank=True)),
                ('full_corp', models.TextField(blank=True)),
                ('corp_rus', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'base_directory',
            },
        ),
        migrations.CreateModel(
            name='ClientDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nnt', models.IntegerField()),
                ('name', models.TextField()),
                ('joint_status', models.BooleanField(default=False)),
                ('number_competitor', models.IntegerField()),
            ],
            options={
                'db_table': 'client_directory',
                'ordering': ['nnt'],
            },
        ),
    ]
