# Generated by Django 3.1 on 2020-10-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_basedirectory_clientdirectory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdirectory',
            old_name='joint_status',
            new_name='matching_status',
        ),
    ]
