# Generated by Django 3.1 on 2020-11-23 16:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20201028_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberCompetitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='test')),
            ],
            options={
                'db_table': 'number_competitor',
            },
        ),
        migrations.AddField(
            model_name='clientdirectory',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdirectory',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),

    ]
