# Generated by Django 3.1 on 2020-12-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_auto_20201123_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdirectory',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
