# Generated by Django 3.1 on 2021-03-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_barcodeeas_eas_synceas'),
    ]

    operations = [
        migrations.AddField(
            model_name='eas',
            name='fv_short',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='synceas',
            name='fv_short',
            field=models.TextField(blank=True),
        ),
    ]
