# Generated by Django 3.1 on 2021-03-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_auto_20210315_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eas',
            name='barcode',
            field=models.ManyToManyField(blank=True, to='directory.BarcodeEAS'),
        ),
        migrations.AlterField(
            model_name='synceas',
            name='barcode',
            field=models.ManyToManyField(blank=True, to='directory.BarcodeEAS'),
        ),
    ]
