# Generated by Django 3.1 on 2021-03-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_auto_20210315_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcodeeas',
            name='barcode_id',
        ),
    ]
