# Generated by Django 3.1 on 2021-03-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_remove_barcodeeas_barcode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synceas',
            name='corp_rus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synceas',
            name='fv_short',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synceas',
            name='trade_name_eng',
            field=models.TextField(blank=True, null=True),
        ),
    ]
