# Generated by Django 3.1 on 2021-03-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_auto_20210315_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synceas',
            name='age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synceas',
            name='corporation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synceas',
            name='divisible_packaging',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synceas',
            name='dosage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synceas',
            name='full_corp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synceas',
            name='manufacturer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synceas',
            name='numero',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synceas',
            name='pack_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synceas',
            name='registration_tm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synceas',
            name='rx_otc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synceas',
            name='size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synceas',
            name='tastes_and_parentheses_fv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synceas',
            name='tn_fv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synceas',
            name='trade_name_rus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synceas',
            name='umbrella_brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synceas',
            name='vendor_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synceas',
            name='volwe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
