# Generated by Django 3.1 on 2021-03-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0015_auto_20210315_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synceas',
            name='barcode',
        ),
        migrations.AddField(
            model_name='synceas',
            name='barcode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
