# Generated by Django 3.1 on 2020-10-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='finalmatching',
            table='final_matching',
        ),
    ]
