# Generated by Django 3.1 on 2020-11-05 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_matching', '0002_auto_20201028_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinalMatching',
        ),
    ]
