# Generated by Django 3.1 on 2021-03-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_matching', '0002_auto_20201028_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerAutoMatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('task_id', models.CharField(max_length=500)),
            ],
        ),
    ]
