# Generated by Django 3.1 on 2021-03-02 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_matching', '0003_workerautomatching'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerAutoMatching',
        ),
    ]
