# Generated by Django 3.1 on 2021-02-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='access_level',
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='qwe', max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AccessLevel',
        ),
    ]
