# Generated by Django 3.1 on 2021-05-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_fedorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fedorlog',
            name='eas_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fedorlog',
            name='sku_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
