# Generated by Django 3.1 on 2021-02-26 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_auto_20201202_1944'),
        ('admin_panel', '0003_auto_20210224_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslevel',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.numbercompetitor'),
        ),
    ]
