# Generated by Django 3.1 on 2021-05-17 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        ('admin_panel', '0003_auto_20210517_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.competitors'),
        ),
    ]
