# Generated by Django 3.1 on 2021-03-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='name',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
