# Generated by Django 3.1 on 2021-03-07 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_tasks_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
