# Generated by Django 3.1 on 2021-03-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_auto_20210307_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_id',
            field=models.CharField(max_length=500),
        ),
    ]
