# Generated by Django 3.1 on 2021-03-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_tasks_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='task',
        ),
    ]
