# Generated by Django 3.1 on 2021-03-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_remove_tasks_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='result',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
