# Generated by Django 3.1 on 2021-03-18 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualMatchingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eas', models.TextField(blank=True)),
                ('name_sku', models.TextField(blank=True)),
                ('lvl', models.FloatField(blank=True)),
                ('lvl2', models.FloatField(blank=True)),
                ('perc_num', models.FloatField(blank=True)),
                ('matching_status', models.BooleanField(default=False)),
                ('number_competitor', models.IntegerField(default=1)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('eas_dict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.basedirectory')),
                ('sku_dict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.clientdirectory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manual_matching_data',
            },
        ),
        migrations.CreateModel(
            name='FinalMatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_binding', models.IntegerField()),
                ('name_binding', models.TextField(blank=True)),
                ('old_type_binding', models.IntegerField(blank=True)),
                ('number_competitor', models.IntegerField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('eas_dict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.basedirectory')),
                ('sku_dict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.clientdirectory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'final_matching',
            },
        ),
    ]
