# Generated by Django 3.1 on 2020-10-28 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualMatchingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sku_dict', models.BigIntegerField(blank=True)),
                ('id_eas_dict', models.BigIntegerField(blank=True)),
                ('name_eas', models.TextField(blank=True)),
                ('name_sku', models.TextField(blank=True)),
                ('matching_status', models.BooleanField(default=False)),
                ('number_competitor', models.IntegerField(default=1)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
