# Generated by Django 3.1 on 2020-10-28 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manual_matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualmatchingdata',
            name='lvl',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manualmatchingdata',
            name='lvl2',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manualmatchingdata',
            name='perc_num',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
