# Generated by Django 3.1 on 2021-05-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_matching', '0002_auto_20210504_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualmatchingdata',
            name='number_competitor',
            field=models.IntegerField(default=1),
        ),
    ]
