# Generated by Django 3.1 on 2020-10-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manual_matching', '0002_auto_20201028_1541'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='manualmatchingdata',
            table='manual_matching_data',
        ),
    ]
