# Generated by Django 3.1 on 2020-11-05 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manual_matching', '0003_auto_20201028_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalMatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sku_dict', models.BigIntegerField()),
                ('id_eas_dict', models.BigIntegerField()),
                ('type_binding', models.IntegerField()),
                ('name_binding', models.TextField(blank=True)),
                ('old_type_binding', models.IntegerField(blank=True)),
                ('number_competitor', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'final_matching',
                'ordering': ['id_sku_dict'],
            },
        ),
    ]
