# Generated by Django 3.1 on 2020-11-05 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20201028_1606'),
        ('manual_matching', '0005_auto_20201105_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmatching',
            name='eas_dict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.basedirectory'),
        ),
        migrations.AlterField(
            model_name='finalmatching',
            name='sku_dict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.clientdirectory'),
        ),
    ]
