# Generated by Django 3.1 on 2021-05-05 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        ('manual_matching', '0005_auto_20210505_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmatching',
            name='eas_dict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.synceas'),
        ),
    ]
