# Generated by Django 3.1 on 2020-11-10 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20201028_1606'),
        ('manual_matching', '0006_auto_20201105_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualmatchingdata',
            name='id_eas_dict',
        ),
        migrations.RemoveField(
            model_name='manualmatchingdata',
            name='id_sku_dict',
        ),
        migrations.AddField(
            model_name='manualmatchingdata',
            name='eas_dict',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='directory.basedirectory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manualmatchingdata',
            name='sku_dict',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='directory.clientdirectory'),
            preserve_default=False,
        ),
    ]
