# Generated by Django 3.1 on 2021-05-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_matching', '0007_auto_20210514_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmatching',
            name='number_competitor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='manualmatchingdata',
            name='number_competitor',
            field=models.IntegerField(default=1),
        ),
    ]
