# Generated by Django 3.1 on 2021-05-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_matching', '0008_auto_20210514_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmatching',
            name='number_competitor',
            field=models.IntegerField(),
        ),
    ]
