# Generated by Django 3.1 on 2020-12-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_matching', '0008_auto_20201123_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmatching',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='finalmatching',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='manualmatchingdata',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='manualmatchingdata',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
