# Generated by Django 3.1 on 2021-04-26 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0017_auto_20210318_1623'),
        ('manual_matching', '0009_auto_20201224_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmatching',
            name='eas_dict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.synceas'),
        ),
        migrations.AlterField(
            model_name='finalmatching',
            name='sku_dict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.syncsku'),
        ),
        migrations.AlterField(
            model_name='manualmatchingdata',
            name='eas_dict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.synceas'),
        ),
        migrations.AlterField(
            model_name='manualmatchingdata',
            name='sku_dict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.syncsku'),
        ),
    ]
