# Generated by Django 3.1 on 2021-04-26 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0017_auto_20210318_1623'),
        ('analytic', '0002_auto_20201224_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingstatistic',
            name='number_competitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.competitors'),
        ),
    ]
