# Generated by Django 3.1 on 2021-05-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0002_auto_20210504_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchingStatistic',
        ),
    ]
